# Generated by Django 3.2 on 2021-04-23 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='testDataPoint',
            fields=[
                ('unique_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('attr1', models.CharField(max_length=60)),
                ('attr2', models.IntegerField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='TestDB',
        ),
    ]
