# ============= COMP90024 - Assignment 2 ============= #
#                               
# The University of Melbourne           
# Team 37
#
# ** Authors: **
# 
# JJ Burke              1048105
# Janelle Tang          694209
# Shuang Qiu            980433
# Declan Baird-Watson   640975
# Avinash Rao           1024577 
# 
# Location: Melbourne
# ==================================================== 

- name: Install pip
  become: yes
  apt:
    name: ['python-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Update pip
  become: yes
  pip:
    name: ['pip']
    state: latest

- name: Install pip3
  become: yes
  apt:
    name: ['python3-pip']
    state: latest
    update_cache: yes
  when: ansible_distribution == "Ubuntu"

- name: Install openstacksdk
  become: yes
  pip:
    name: ['openstacksdk']
    state: latest

#- name: Change pip3 to pip.
#  become: yes
#  command: update-alternatives --install /usr/bin/pip pip /usr/bin/pip3 1
