---
- name: pull latest code from git
  git:
    repo: ssh://git@github.com/JanelleTang/COMP90024_Assignment_2.git
    key_file: /home/ubuntu/.ssh/github
    update: yes
    dest: '{{ remote_working_directory }}'
    force: yes

- name: install node modules
  command:
    cmd: npm install
    chdir: '{{ frontend_directory }}'

- name: generate dist file for frontend
  command:
    cmd: npm run build
    chdir: '{{ frontend_directory }}'


- name: invoke docker compose to create container
  become: yes
  command: 
    cmd: docker-compose up --build -d --force-recreate
    chdir: '{{remote_working_directory}}/backend'