---
- name: pull latest code from git
  git:
    repo: ssh://git@github.com/JanelleTang/COMP90024_Assignment_2.git
    key_file: /home/ubuntu/.ssh/GitHub
    update: yes
    dest: '{{ remote_working_directory }}'
    force: yes

- name: copy compose file to server
  template:
    src: instance3-docker-compose.yaml.j2
    dest: '/home/ubuntu/docker-compose.yaml'
    owner: ubuntu
    group: ubuntu