# Generated by Django 3.2 on 2021-05-05 06:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('VIC', 'Victoria'), ('NSW', 'New South Wales'), ('QLD', 'Queensland'), ('SA', 'South Australia')], max_length=3)),
                ('city', models.BooleanField(default=False)),
                ('polygon', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
                ('sentiment_value', models.DecimalField(decimal_places=2, max_digits=3)),
                ('sentiment_rank', models.IntegerField(choices=[(1, 'Extreme Neg'), (2, 'Neg'), (3, 'Neutral'), (4, 'Pos'), (5, 'Extreme Pos')], default=3)),
                ('n_tweets', models.IntegerField()),
            ],
        ),
    ]
