# Generated by Django 3.2 on 2021-05-22 10:35

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('victoria', 'Victoria'), ('new south wales', 'New South Wales'), ('queensland', 'Queensland'), ('south australia', 'South Australia'), ('tasmania', 'Tasmania'), ('western australia', 'Western Australia')], max_length=20)),
                ('polygon', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('sentiment_value', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('sentiment_rank', models.IntegerField(choices=[(-3, 'Extreme Neg'), (-2, 'Neg'), (-1, 'Slight Neg'), (0, 'Neutral'), (1, 'Slight Pos'), (2, 'Pos'), (3, 'Extreme Pos')], default=0)),
                ('n_tweets', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('display_name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('state', models.CharField(choices=[('victoria', 'Victoria'), ('new south wales', 'New South Wales'), ('queensland', 'Queensland'), ('south australia', 'South Australia'), ('tasmania', 'Tasmania'), ('western australia', 'Western Australia')], max_length=20)),
                ('polygon', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('sentiment_value', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('sentiment_rank', models.IntegerField(choices=[(-3, 'Extreme Neg'), (-2, 'Neg'), (-1, 'Slight Neg'), (0, 'Neutral'), (1, 'Slight Pos'), (2, 'Pos'), (3, 'Extreme Pos')], default=3)),
                ('n_tweets', models.IntegerField(default=0)),
            ],
        ),
    ]
