# Generated by Django 3.2 on 2021-05-14 11:58

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('victoria', 'Victoria'), ('new south wales', 'New South Wales'), ('queensland', 'Queensland'), ('south australia', 'South Australia')], max_length=20)),
                ('polygon', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('sentiment_value', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('sentiment_rank', models.IntegerField(choices=[(1, 'Extreme Neg'), (2, 'Neg'), (3, 'Neutral'), (4, 'Pos'), (5, 'Extreme Pos')], default=3)),
                ('n_tweets', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LGA',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('victoria', 'Victoria'), ('new south wales', 'New South Wales'), ('queensland', 'Queensland'), ('south australia', 'South Australia')], max_length=20)),
                ('polygon', django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326)),
                ('sentiment_value', models.DecimalField(decimal_places=4, default=0, max_digits=20)),
                ('sentiment_rank', models.IntegerField(choices=[(1, 'Extreme Neg'), (2, 'Neg'), (3, 'Neutral'), (4, 'Pos'), (5, 'Extreme Pos')], default=3)),
                ('n_tweets', models.IntegerField(default=0)),
            ],
        ),
    ]
