
# ============= COMP90024 - Assignment 2 ============= #
#                               
# The University of Melbourne           
# Team 37
#
# ** Authors: **
# 
# JJ Burke              1048105
# Janelle Tang          694209
# Shuang Qiu            980433
# Declan Baird-Watson   640975
# Avinash Rao           1024577 
# 
# Location: Melbourne
# ==================================================== 
---
project_working_directory: /Users/shuangqiu/Desktop/COMP90024_ASSIGNMENT_2/Ansible
remote_working_directory: /home/ubuntu/COMP90024
frontend_directory: /home/ubuntu/COMP90024/backend/frontend
proxy_address: http://wwwproxy.unimelb.edu.au:8000/
