# COMP90024 Project - Team 37

---
-hosts: localhost
# Variables
availability_zone: melbourne-qh2-uom
instance_image: 916cad7a-c545-48b2-b36c-d509ee63b3ce #NeCTAR Ubuntu 18.04 LTS (Bionic) amd64 (with Docker)
instance_network: qh2-uom-internal
instance_key_name: dev-testing
#ansible_python_interpreter: /Library/Frameworks/Python.framework/Versions/3.7/bin/python3
#ansible_python_interpreter: /Users/shuangqiu/.pyenv/versions/3.6.10/bin/python
project_directory: /Users/shuangqiu/Desktop/COMP90024_Assignment_2/Ansible
#ansible_ssh_private_key_file: ~/.ssh/dev-testing.pem
# # For Volume Variables
volumes:
  - vol_name: instance1-vol
    vol_size: 160
    device: /dev/vdb
    mountpoint: /data
  - vol_name: instance2-vol
    vol_size: 160
    device: /dev/vdb
    mountpoint: /data
  - vol_name: instance3-vol
    vol_size: 160
    device: /dev/vdb
    mountpoint: /data
  - vol_name: instance4-vol
    vol_size: 20
    device: /dev/vdb
    mountpoint: /data
#
# For Security group Variables
security_groups:
  - name: instance1-security-group
    description: "security groups"
    protocol: tcp
    port_range_min: 1
    port_range_max: 65535
    remote_ip_prefix: 0.0.0.0/0


instances:
- instance_name: instance1
  instance_vol_name: instance1-vol
  instance_flavor: uom.mse.2c9g
- instance_name: instance2
  instance_vol_name: instance2-vol
  instance_flavor: uom.mse.2c9g
- instance_name: instance3
  instance_vol_name: instance3-vol
  instance_flavor: uom.mse.2c9g
- instance_name: instance4
  instance_vol_name: instance4-vol
  instance_flavor: uom.mse.1c4g

  
