- name: Make file system
  become: yes
  filesystem:
    fstype: xfs
    dev: "{{ item.device }}"
  when: item.device is defined
  loop: "{{ volumes }}"


- name: Checking folders
  become: yes
  stat:
    path: "{{ item.mountpoint }}"
  register: stats
  loop: "{{ volumes }}"

- name: Create directory
  become: yes
  file:
    path: "{{ item.item.mountpoint }}"
    recurse: yes
    state: directory
  when: item.stat.exists == false
  loop: "{{ stats.results }}"

- name: Mount device
  become: yes
  mount:
    path: "{{ item.mountpoint }}"
    src: "{{ item.device }}"
    fstype: xfs
    state: mounted
  when: item.device is defined
  loop: "{{ volumes }}"
