---
- name: Update apt
  become: yes
  apt:
    upgrade: yes
    update_cache: yes


- name: install dependencies
  become: yes
  apt:
    name: ['vim','git','unzip','python3-pip','xfsprogs','ca-certificates','apt-transport-https','curl','python-setuptools','software-properties-common']
    state: latest
    install_recommends: no
    update_cache: yes

- name: add apt repository
  become: yes
  shell: add-apt-repository ppa:ubuntugis/ppa

- name: Install docker-ce
  become: yes
  apt:
    name: ['docker-ce']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Install docker
  become: yes
  apt:
    name: ['docker']
    state: latest
    install_recommends: no
    update_cache: yes

# - name: Install docker-compose
#   become: yes
#   pip:
#     name: ['docker-compose']
#     version: 1.22.0
#     state: present

- name: Downloading the docker compose
  become: yes
  shell: curl -L "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: Add executable permission to the binary
  become: yes
  file:
    dest: /usr/local/bin/docker-compose
    mode: a+x