# ============= COMP90024 - Assignment 2 ============= #
#                               
# The University of Melbourne           
# Team 37
#
# ** Authors: **
# 
# JJ Burke              1048105
# Janelle Tang          694209
# Shuang Qiu            980433
# Declan Baird-Watson   640975
# Avinash Rao           1024577 
# 
# Location: Melbourne
# ==================================================== 
---
- name: Update apt
  become: yes
  apt:
    upgrade: yes
    update_cache: yes


- name: install dependencies
  become: yes
  apt:
    name: ['vim','git','unzip','python-pip','python3-pip','xfsprogs','ca-certificates','apt-transport-https','curl','python-setuptools','software-properties-common']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Install pexpect
  become: yes
  pip:
    name: pexpect

- name: add apt repository
  become: yes
  shell: yes '' | add-apt-repository ppa:ubuntugis/ppa

- name: Install docker-ce
  become: yes
  apt:
    name: ['docker-ce']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Install docker
  become: yes
  apt:
    name: ['docker']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Downloading the docker compose
  become: yes
  shell: curl -L "https://github.com/docker/compose/releases/download/1.29.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose

- name: Add executable permission to the binary
  become: yes
  file:
    dest: /usr/local/bin/docker-compose
    mode: a+x

- name: Downloading node.js 10
  become: yes
  shell: curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash

- name: install node.js 10
  become: yes
  shell: apt -y install nodejs make gcc g++
