---
- name: add proxy to enviroments
  become: yes
  lineinfile:
    line: "http_proxy=\"{{ proxy_address }}\"\nhttps_proxy=\"{{ proxy_address }}\"\nftp_proxy=\"{{ proxy_address }}\"\nno_proxy=\"localhost,127.0.0.1,127.0.1.1,0.0.0.0,ubuntu,instance1\"\n"
    dest: /etc/environment

- name: make proxy available for current session
  become: yes
  environment:
    http_proxy: "{{ proxy_address }}"
    https_proxy: "{{ proxy_address }}"
    ftp_proxy: "{{ proxy_address }}"
    no_proxy: "localhost,127.0.0.1,127.0.1.1,0.0.0.0,ubuntu,instance1"

- name: Update apt
  become: yes
  apt:
    upgrade: yes
    update_cache: yes

- name: install dependencies
  become: yes
  apt:
    name: ['vim','git','unzip','python-pip','xfsprogs','ca-certificates','apt-transport-https','curl','python-setuptools','software-properties-common']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Add Docker apt repository key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker apt repository and update cache
  become: yes
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    mode: '644'
    update_cache: yes
    state: present

- name: Install docker
  become: yes
  apt:
    name: ['docker-ce']
    state: latest
    install_recommends: no
    update_cache: yes

- name: Install docker-compose
  become: yes
  pip:
    name: ['docker-compose']
    version: 1.22.0
    state: present