# Generated by Django 3.2 on 2021-05-05 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('state', models.CharField(choices=[('VIC', 'Victoria'), ('NSW', 'New South Wales'), ('QLD', 'Queensland'), ('SA', 'South Australia')], max_length=3)),
                ('city', models.BooleanField(default=False)),
                ('polygon', models.CharField(max_length=10000)),
                ('sentiment_value', models.DecimalField(decimal_places=3, max_digits=3)),
                ('n_tweets', models.IntegerField()),
            ],
        ),
    ]
