
# ============= COMP90024 - Assignment 2 ============= #
#                               
# The University of Melbourne           
# Team 37
#
# ** Authors: **
# 
# JJ Burke              1048105
# Janelle Tang          694209
# Shuang Qiu            980433
# Declan Baird-Watson   640975
# Avinash Rao           1024577 
# 
# Location: Melbourne
# ==================================================== 

---
- hosts: all
  vars_files:
    - Variables/Environment_variables.yaml
    - Variables/Host_variables.yaml
  gather_facts: true
  roles:
    - role: Install_Environments
    - role: Clone_Repository
    - role: Mount_Volume
