# COMP90024 Project - Team 37

---
- hosts: localhost
  vars_files:
    - Variables/Host_variables.yaml
    - Variables/Environment_variables.yaml
  gather_facts: true

  roles:
    - role: Install_Environments