---
- hosts: localhost
  vars_files:
    - Variables/Host_variables.yaml
  gather_facts: true
  roles:
    - role: Common
    - role: Volumes
    - role: Security_Groups
    - role: Instances
