# COMP90024 Project - Team 37
# Create volumes from vars 
- name: Create volume
  os_volume:
    display_name: '{{ item.vol_name }}'
    size: '{{ item.vol_size }}'
    availability_zone: '{{ availability_zone }}'
    wait: yes
    timeout: 600
    state: present
  loop: '{{ volumes }}'
  register: os_vol

- debug:
    msg: Volumes created
